// OTOMATIK URETILDI + insan uzlastirmasi — ArduPilot SERVOx_FUNCTION enumu.
// 3 bagimsiz ajan uretimi, >=2 mutabakat ile uzlastirildi (B+C SRV_Channel.h WebFetch ile dogruladi).
// Kaynak: ArduPilot SRV_Channel Aux_servo_function_t (Plane/Copter 4.4-4.5).
import type { CodeLabel } from './ardupilot-rc';
export type { CodeLabel };

/** SERVOx_FUNCTION tam enum (-1 GPIO .. 155). */
export const SERVO_FUNCTIONS: readonly CodeLabel[] = [
  { code: -1, label: 'GPIO' },
  { code: 0, label: 'Disabled' },
  { code: 1, label: 'RCPassThru' },
  { code: 2, label: 'Flap' },
  { code: 3, label: 'Flap Auto' },
  { code: 4, label: 'Aileron' },
  { code: 6, label: 'Mount1 Yaw' },
  { code: 7, label: 'Mount1 Pitch' },
  { code: 8, label: 'Mount1 Roll' },
  { code: 9, label: 'Mount1 Open' },
  { code: 10, label: 'Camera Trigger' },
  { code: 11, label: 'Egg Drop (deprecated)' },
  { code: 12, label: 'Mount2 Yaw' },
  { code: 13, label: 'Mount2 Pitch' },
  { code: 14, label: 'Mount2 Roll' },
  { code: 15, label: 'Mount2 Open' },
  { code: 16, label: 'Differential Spoiler Left 1' },
  { code: 17, label: 'Differential Spoiler Right 1' },
  { code: 18, label: 'Aileron with Input (deprecated)' },
  { code: 19, label: 'Elevator' },
  { code: 20, label: 'Elevator with Input (deprecated)' },
  { code: 21, label: 'Rudder' },
  { code: 22, label: 'Sprayer Pump' },
  { code: 23, label: 'Sprayer Spinner' },
  { code: 24, label: 'Flaperon Left' },
  { code: 25, label: 'Flaperon Right' },
  { code: 26, label: 'Ground Steering' },
  { code: 27, label: 'Parachute Release' },
  { code: 28, label: 'Gripper' },
  { code: 29, label: 'Landing Gear' },
  { code: 30, label: 'Engine Run Enable' },
  { code: 31, label: 'Heli RSC' },
  { code: 32, label: 'Heli Tail RSC' },
  { code: 33, label: 'Motor 1' },
  { code: 34, label: 'Motor 2' },
  { code: 35, label: 'Motor 3' },
  { code: 36, label: 'Motor 4' },
  { code: 37, label: 'Motor 5' },
  { code: 38, label: 'Motor 6' },
  { code: 39, label: 'Motor 7' },
  { code: 40, label: 'Motor 8' },
  { code: 41, label: 'Motor Tilt' },
  { code: 42, label: 'Generator Control' },
  { code: 45, label: 'Tilt Motor Rear' },
  { code: 46, label: 'Tilt Motor Rear Left' },
  { code: 47, label: 'Tilt Motor Rear Right' },
  { code: 51, label: 'RCIN1' },
  { code: 52, label: 'RCIN2' },
  { code: 53, label: 'RCIN3' },
  { code: 54, label: 'RCIN4' },
  { code: 55, label: 'RCIN5' },
  { code: 56, label: 'RCIN6' },
  { code: 57, label: 'RCIN7' },
  { code: 58, label: 'RCIN8' },
  { code: 59, label: 'RCIN9' },
  { code: 60, label: 'RCIN10' },
  { code: 61, label: 'RCIN11' },
  { code: 62, label: 'RCIN12' },
  { code: 63, label: 'RCIN13' },
  { code: 64, label: 'RCIN14' },
  { code: 65, label: 'RCIN15' },
  { code: 66, label: 'RCIN16' },
  { code: 67, label: 'Ignition' },
  { code: 69, label: 'Starter' },
  { code: 70, label: 'Throttle' },
  { code: 71, label: 'Tracker Yaw' },
  { code: 72, label: 'Tracker Pitch' },
  { code: 73, label: 'Throttle Left' },
  { code: 74, label: 'Throttle Right' },
  { code: 75, label: 'Tilt Motor Left' },
  { code: 76, label: 'Tilt Motor Right' },
  { code: 77, label: 'Elevon Left' },
  { code: 78, label: 'Elevon Right' },
  { code: 79, label: 'VTail Left' },
  { code: 80, label: 'VTail Right' },
  { code: 81, label: 'Boost Throttle' },
  { code: 82, label: 'Motor 9' },
  { code: 83, label: 'Motor 10' },
  { code: 84, label: 'Motor 11' },
  { code: 85, label: 'Motor 12' },
  { code: 86, label: 'Differential Spoiler Left 2' },
  { code: 87, label: 'Differential Spoiler Right 2' },
  { code: 88, label: 'Winch' },
  { code: 89, label: 'Main Sail Sheet' },
  { code: 90, label: 'Camera ISO' },
  { code: 91, label: 'Camera Aperture' },
  { code: 92, label: 'Camera Focus' },
  { code: 93, label: 'Camera Shutter Speed' },
  { code: 94, label: 'Script 1' },
  { code: 95, label: 'Script 2' },
  { code: 96, label: 'Script 3' },
  { code: 97, label: 'Script 4' },
  { code: 98, label: 'Script 5' },
  { code: 99, label: 'Script 6' },
  { code: 100, label: 'Script 7' },
  { code: 101, label: 'Script 8' },
  { code: 102, label: 'Script 9' },
  { code: 103, label: 'Script 10' },
  { code: 104, label: 'Script 11' },
  { code: 105, label: 'Script 12' },
  { code: 106, label: 'Script 13' },
  { code: 107, label: 'Script 14' },
  { code: 108, label: 'Script 15' },
  { code: 109, label: 'Script 16' },
  { code: 110, label: 'Airbrake' },
  { code: 120, label: 'NeoPixel 1' },
  { code: 121, label: 'NeoPixel 2' },
  { code: 122, label: 'NeoPixel 3' },
  { code: 123, label: 'NeoPixel 4' },
  { code: 124, label: 'Rate Roll' },
  { code: 125, label: 'Rate Pitch' },
  { code: 126, label: 'Rate Thrust' },
  { code: 127, label: 'Rate Yaw' },
  { code: 128, label: 'Wingsail Elevator' },
  { code: 129, label: 'ProfiLED 1' },
  { code: 130, label: 'ProfiLED 2' },
  { code: 131, label: 'ProfiLED 3' },
  { code: 132, label: 'ProfiLED Clock' },
  { code: 133, label: 'Winch Clutch' },
  { code: 134, label: 'SERVO Min' },
  { code: 135, label: 'SERVO Trim' },
  { code: 136, label: 'SERVO Max' },
  { code: 137, label: 'Mast Rotation' },
  { code: 138, label: 'Alarm' },
  { code: 139, label: 'Alarm Inverted' },
  { code: 140, label: 'RCIN1 Scaled' },
  { code: 141, label: 'RCIN2 Scaled' },
  { code: 142, label: 'RCIN3 Scaled' },
  { code: 143, label: 'RCIN4 Scaled' },
  { code: 144, label: 'RCIN5 Scaled' },
  { code: 145, label: 'RCIN6 Scaled' },
  { code: 146, label: 'RCIN7 Scaled' },
  { code: 147, label: 'RCIN8 Scaled' },
  { code: 148, label: 'RCIN9 Scaled' },
  { code: 149, label: 'RCIN10 Scaled' },
  { code: 150, label: 'RCIN11 Scaled' },
  { code: 151, label: 'RCIN12 Scaled' },
  { code: 152, label: 'RCIN13 Scaled' },
  { code: 153, label: 'RCIN14 Scaled' },
  { code: 154, label: 'RCIN15 Scaled' },
  { code: 155, label: 'RCIN16 Scaled' },
];

const sfMap = new Map(SERVO_FUNCTIONS.map((o) => [o.code, o.label]));
export const servoFuncLabel = (code: number): string => sfMap.get(code) ?? ('Bilinmeyen (' + code + ')');

/** Ucak kumanda yuzeyi -> SERVO fonksiyon kodu. */
export const PLANE_SURFACES: Record<string, { code: number; label: string }> = {
  disabled: { code: 0, label: 'Disabled' },
  rc_passthru: { code: 1, label: 'RCPassThru' },
  flap: { code: 2, label: 'Flap' },
  flap_auto: { code: 3, label: 'Flap Auto' },
  aileron: { code: 4, label: 'Aileron' },
  elevator: { code: 19, label: 'Elevator' },
  rudder: { code: 21, label: 'Rudder' },
  flaperon_left: { code: 24, label: 'Flaperon Left' },
  flaperon_right: { code: 25, label: 'Flaperon Right' },
  throttle: { code: 70, label: 'Throttle (Main)' },
  throttle_left: { code: 73, label: 'Throttle Left' },
  throttle_right: { code: 74, label: 'Throttle Right' },
  elevon_left: { code: 77, label: 'Elevon Left' },
  elevon_right: { code: 78, label: 'Elevon Right' },
  vtail_left: { code: 79, label: 'VTail Left' },
  vtail_right: { code: 80, label: 'VTail Right' },
};

/** Ucak tipi -> gosterilecek yuzey anahtarlari (sirali). */
// Her uçak tipi çok-motorlu olabilir: ana + sol + sağ motor çıkışları eklenir.
export const PLANE_LAYOUTS: Record<'standard' | 'elevon' | 'vtail', string[]> = {
  standard: ['aileron', 'elevator', 'rudder', 'throttle', 'throttle_left', 'throttle_right'],
  elevon: ['elevon_left', 'elevon_right', 'rudder', 'throttle', 'throttle_left', 'throttle_right'],
  vtail: ['aileron', 'vtail_left', 'vtail_right', 'throttle', 'throttle_left', 'throttle_right'],
};
