// OTOMATIK URETILDI + insan uzlastirmasi — ArduPilot RC enumleri.
// 3 bagimsiz ajan uretimi, >=2 mutabakat ile uzlastirildi (celisen 153-164 kodlari haric).
// Kaynak: ArduPilot Copter/Plane 4.4-4.5 (RC_Channel AUX_FUNC, RC_PROTOCOLS, RC_OPTIONS, RSSI_TYPE).

export interface CodeLabel { code: number; label: string; }
export interface BitLabel { bit: number; label: string; }

/** RCx_OPTION — yardimci anahtar fonksiyonlari. */
export const RC_AUX_OPTIONS: readonly CodeLabel[] = [
  { code: 0, label: 'Do Nothing' },
  { code: 2, label: 'Flip' },
  { code: 3, label: 'Simple Mode' },
  { code: 4, label: 'RTL' },
  { code: 5, label: 'Save Trim' },
  { code: 7, label: 'Save Waypoint' },
  { code: 9, label: 'Camera Trigger' },
  { code: 10, label: 'RangeFinder Enable' },
  { code: 11, label: 'Fence Enable' },
  { code: 13, label: 'Super Simple Mode' },
  { code: 14, label: 'Acro Trainer' },
  { code: 15, label: 'Sprayer Enable' },
  { code: 16, label: 'Auto' },
  { code: 17, label: 'AutoTune' },
  { code: 18, label: 'Land' },
  { code: 19, label: 'Gripper' },
  { code: 21, label: 'Parachute Enable' },
  { code: 22, label: 'Parachute Release' },
  { code: 23, label: 'Parachute 3-Position' },
  { code: 24, label: 'Auto Mission Reset' },
  { code: 25, label: 'AttCon Feed Forward' },
  { code: 26, label: 'AttCon Accel Limits' },
  { code: 27, label: 'Retract Mount1' },
  { code: 28, label: 'Relay1 On/Off' },
  { code: 29, label: 'Landing Gear' },
  { code: 30, label: 'Lost Vehicle Sound' },
  { code: 31, label: 'Motor Emergency Stop' },
  { code: 32, label: 'Motor Interlock' },
  { code: 33, label: 'Brake' },
  { code: 34, label: 'Relay2 On/Off' },
  { code: 35, label: 'Relay3 On/Off' },
  { code: 36, label: 'Relay4 On/Off' },
  { code: 37, label: 'Throw' },
  { code: 38, label: 'ADSB Avoidance Enable' },
  { code: 39, label: 'Precision Loiter' },
  { code: 40, label: 'Proximity Avoidance' },
  { code: 41, label: 'Arm/Disarm' },
  { code: 42, label: 'SmartRTL' },
  { code: 43, label: 'Inverted Flight' },
  { code: 44, label: 'Winch Enable' },
  { code: 45, label: 'Winch Control' },
  { code: 46, label: 'RC Override Enable' },
  { code: 47, label: 'User Function 1' },
  { code: 48, label: 'User Function 2' },
  { code: 49, label: 'User Function 3' },
  { code: 50, label: 'Learn Cruise (Rover)' },
  { code: 51, label: 'Manual' },
  { code: 52, label: 'Acro' },
  { code: 53, label: 'Steering (Rover)' },
  { code: 54, label: 'Hold (Rover)' },
  { code: 55, label: 'Guided' },
  { code: 56, label: 'Loiter' },
  { code: 57, label: 'Follow' },
  { code: 58, label: 'Clear Waypoints' },
  { code: 59, label: 'Simple (Rover)' },
  { code: 60, label: 'ZigZag' },
  { code: 61, label: 'ZigZag Save Waypoint' },
  { code: 62, label: 'Compass Learn' },
  { code: 63, label: 'Sailboat Tack' },
  { code: 64, label: 'Reverse Throttle' },
  { code: 65, label: 'GPS Disable' },
  { code: 66, label: 'Relay5 On/Off' },
  { code: 67, label: 'Relay6 On/Off' },
  { code: 68, label: 'Stabilize' },
  { code: 69, label: 'PosHold' },
  { code: 70, label: 'AltHold' },
  { code: 71, label: 'FlowHold' },
  { code: 72, label: 'Circle' },
  { code: 73, label: 'Drift' },
  { code: 74, label: 'Sailboat Motor 3-Position' },
  { code: 75, label: 'Surface Tracking' },
  { code: 76, label: 'Standby Mode' },
  { code: 77, label: 'Takeoff' },
  { code: 78, label: 'RunCam Control' },
  { code: 79, label: 'RunCam OSD Control' },
  { code: 80, label: 'Visual Odometry Align' },
  { code: 81, label: 'Disarm' },
  { code: 82, label: 'Q Assist (QuadPlane)' },
  { code: 83, label: 'ZigZag Auto' },
  { code: 84, label: 'AirMode' },
  { code: 85, label: 'Generator' },
  { code: 86, label: 'Non Auto Terrain Disable (Plane)' },
  { code: 87, label: 'Crow Select (Plane)' },
  { code: 88, label: 'Soaring Enable' },
  { code: 89, label: 'Landing Flare (Plane)' },
  { code: 90, label: 'EKF Position Source' },
  { code: 91, label: 'Airspeed Calibrate' },
  { code: 92, label: 'FBWA (Plane)' },
  { code: 93, label: 'Relocate Mission' },
  { code: 94, label: 'VTX Power' },
  { code: 95, label: 'FBWA Taildragger (Plane)' },
  { code: 96, label: 'Mode Switch Reset' },
  { code: 97, label: 'Wind Vane Direction Offset' },
  { code: 98, label: 'Training (Plane)' },
  { code: 99, label: 'Auto RTL' },
  { code: 100, label: 'Kill IMU1' },
  { code: 101, label: 'Kill IMU2' },
  { code: 102, label: 'Camera Mode Toggle' },
  { code: 103, label: 'EKF Lane Switch' },
  { code: 104, label: 'EKF Yaw Reset' },
  { code: 105, label: 'GPS Disable Yaw' },
  { code: 106, label: 'Disable Airspeed Use' },
  { code: 107, label: 'Fixed Wing AutoTune' },
  { code: 108, label: 'QRTL (QuadPlane)' },
  { code: 109, label: 'Custom Controller' },
  { code: 110, label: 'Kill IMU3' },
  { code: 113, label: 'Retract Mount2' },
  { code: 150, label: 'Cruise (Rover)' },
  { code: 151, label: 'Turtle' },
  { code: 152, label: 'Simple Heading Reset' },
];

/** RC_PROTOCOLS bitmask bitleri (0-tabanli). bit0=All = otomatik hepsi. */
export const RC_PROTOCOL_BITS: readonly BitLabel[] = [
  { bit: 0, label: 'All' },
  { bit: 1, label: 'PPM' },
  { bit: 2, label: 'IBUS' },
  { bit: 3, label: 'SBUS' },
  { bit: 4, label: 'SBUS_NI (non-inverted)' },
  { bit: 5, label: 'DSM (Spektrum)' },
  { bit: 6, label: 'SUMD' },
  { bit: 7, label: 'SRXL' },
  { bit: 8, label: 'SRXL2' },
  { bit: 9, label: 'CRSF' },
  { bit: 10, label: 'ST24' },
  { bit: 11, label: 'FPort' },
  { bit: 12, label: 'FPort2' },
  { bit: 13, label: 'FastSBUS' },
  { bit: 14, label: 'DroneCAN' },
  { bit: 15, label: 'Ghost (GHST)' },
  { bit: 16, label: 'MAVLink Radio (MAVRadio)' },
];

/** RC_OPTIONS bitmask bitleri. */
export const RC_OPTION_BITS: readonly BitLabel[] = [
  { bit: 0, label: 'Ignore RC Receiver' },
  { bit: 1, label: 'Ignore MAVLink Overrides' },
  { bit: 2, label: 'Ignore Receiver Failsafe bit' },
  { bit: 3, label: 'FPort Pad' },
  { bit: 4, label: 'Log RC input bytes' },
  { bit: 5, label: 'Arming check throttle for 0 input' },
  { bit: 6, label: 'Skip arming check for neutral Roll/Pitch/Yaw sticks' },
  { bit: 7, label: 'Allow Switch reverse' },
  { bit: 8, label: 'Use passthrough for CRSF telemetry' },
  { bit: 9, label: 'Suppress CRSF mode/rate message for ELRS' },
  { bit: 10, label: 'Enable multiple receiver support' },
  { bit: 11, label: 'Use Link Quality for RSSI with CRSF' },
  { bit: 12, label: 'Annotate CRSF flight mode with * on disarm' },
  { bit: 13, label: 'Use 420kbaud for ELRS protocol' },
  { bit: 14, label: 'Clear MAVLink overrides on any stick input' },
];

/** RSSI_TYPE degerleri. */
export const RSSI_TYPES: readonly CodeLabel[] = [
  { code: 0, label: 'Disabled' },
  { code: 1, label: 'AnalogPin' },
  { code: 2, label: 'RCChannelPwmValue' },
  { code: 3, label: 'ReceiverProtocol' },
  { code: 4, label: 'PWMInputPin' },
  { code: 5, label: 'TelemetryRadioRSSI' },
];

/** SERIALx_PROTOCOL = 23 -> RC girisi (RCIN). Bir UART'a bagli alicilar (CRSF/ELRS/FPort) icin. */
export const SERIAL_PROTOCOL_RCIN = 23;

const auxMap = new Map(RC_AUX_OPTIONS.map((o) => [o.code, o.label]));
export const auxLabel = (code: number): string => auxMap.get(code) ?? ('Bilinmeyen (' + code + ')');
