// Setup bölümleri için sayfa-özel yardım (ne + neden + nasıl). Kısa ve öğretici.
// i18n dosyalarını şişirmemek için burada tutulur; SetupView geçerli dile göre gösterir.
export interface HelpEntry { title: string; body: string; tips: string[] }
type Lang = 'tr' | 'en' | 'de';

export const SETUP_HELP: Record<string, Record<Lang, HelpEntry>> = {
  firmware: {
    tr: { title: 'Firmware', body: 'Uçuş kontrolcüsüne ArduPilot yazılımını yükler ya da yükseltir. Karta seri bootloader (USB) veya DFU ile yazabilir, ya da ArduPilot sürümünü doğrudan indirebilirsiniz.', tips: ['Kartı bootloader modunda USB’ye bağlayın (Chromium/Edge).', 'Tam kart modelinizi seçin — yanlış firmware kartı çalışmaz hale getirir.', '.apj kart uyumunu kontrol eder; ham .bin etmez.'] },
    en: { title: 'Firmware', body: 'Installs or upgrades the ArduPilot software on the flight controller. Flash over the serial bootloader (USB) or DFU, or download a version straight from ArduPilot.', tips: ['Connect the board in bootloader mode over USB (Chromium/Edge).', 'Pick your exact board — the wrong firmware can brick it.', '.apj verifies the board; a raw .bin does not.'] },
    de: { title: 'Firmware', body: 'Installiert oder aktualisiert die ArduPilot-Software auf dem Flight Controller. Über den seriellen Bootloader (USB) oder DFU flashen oder eine Version direkt von ArduPilot laden.', tips: ['Board im Bootloader-Modus per USB verbinden (Chromium/Edge).', 'Genaues Board wählen — falsche Firmware kann es unbrauchbar machen.', '.apj prüft das Board, ein rohes .bin nicht.'] },
  },
  orient: {
    tr: { title: 'Kart Yönelimi', body: 'Otopilot kartının uçak gövdesine göre montaj yönünü (AHRS_ORIENTATION) ayarlar. Kart okla ileri, düz monte edilmediyse otopilot tutumu yanlış ölçer — 3D görünümde kartı gerçekte durduğu gibi döndürün.', tips: ['Karttaki ok, uçuş yönünü göstermelidir; farklıysa burada seçin.', 'Değişiklikten sonra yeniden başlatın; ivmeölçer ve pusulayı yeniden kalibre edin.', 'Doğrulama: burnu kaldırınca pitch, sağa yatırınca roll artmalı.'] },
    en: { title: 'Board Orientation', body: 'Sets how the autopilot board is mounted relative to the airframe (AHRS_ORIENTATION). If the board is not flat with the arrow forward, attitude is measured wrong — rotate the board in the 3D view to match how it actually sits.', tips: ['The board arrow should point in the flight direction; if not, pick the rotation here.', 'Reboot after changing; redo the accel and compass calibrations.', 'Verify: nose up should raise pitch, right bank should raise roll.'] },
    de: { title: 'Boardausrichtung', body: 'Legt fest, wie das Autopilot-Board relativ zur Zelle montiert ist (AHRS_ORIENTATION). Liegt das Board nicht flach mit Pfeil nach vorn, wird die Lage falsch gemessen — Board in der 3D-Ansicht so drehen, wie es tatsächlich sitzt.', tips: ['Der Pfeil auf dem Board soll in Flugrichtung zeigen; sonst hier die Drehung wählen.', 'Nach der Änderung neu starten; Beschleunigungs- und Kompasskalibrierung wiederholen.', 'Prüfen: Nase hoch → Pitch steigt, rechts kippen → Roll steigt.'] },
  },
  accel: {
    tr: { title: 'İvmeölçer', body: 'Aracın yatay/eğim referansını belirleyen 6-pozisyon ivmeölçer kalibrasyonu. Yapılmazsa yapay ufuk ve irtifa sürüklenir.', tips: ['Düz, sağlam bir zeminde yapın.', 'Her pozisyonu ekrandaki gibi hareketsiz tutun.', 'Titreşim/hareket varken yapmayın.'] },
    en: { title: 'Accelerometer', body: 'The 6-position accel calibration that sets the vehicle’s level/attitude reference. Skip it and the artificial horizon and altitude drift.', tips: ['Do it on a flat, solid surface.', 'Hold each orientation still, as shown on screen.', 'Don’t calibrate with vibration or movement.'] },
    de: { title: 'Beschleunigungssensor', body: 'Die 6-Positionen-Kalibrierung, die die Lage-/Horizontreferenz festlegt. Ohne sie driften künstlicher Horizont und Höhe.', tips: ['Auf ebener, fester Fläche durchführen.', 'Jede Ausrichtung ruhig halten, wie am Bildschirm gezeigt.', 'Nicht bei Vibration/Bewegung kalibrieren.'] },
  },
  compass: {
    tr: { title: 'Pusula', body: 'Manyetometreyi kalibre eder — küre, taranan yönleri gösterir. Doğru yön/başlık için şarttır; kötü pusula EKF hatası ve “tuvalet çanağı” dönmesine yol açar.', tips: ['Metal, mıknatıs ve güçlü akımlardan uzak durun.', 'Tüm eksenlerde yavaşça çevirin; kırmızı bölgeler kalmasın.', 'Telefon/hoparlörü yaklaştırmayın.'] },
    en: { title: 'Compass', body: 'Calibrates the magnetometer — the sphere shows which directions are sampled. Essential for correct heading; a bad compass causes EKF errors and “toilet-bowling”.', tips: ['Keep away from metal, magnets and high current.', 'Rotate slowly on all axes until no red areas remain.', 'Keep phones/speakers away.'] },
    de: { title: 'Kompass', body: 'Kalibriert das Magnetometer — die Kugel zeigt die erfassten Richtungen. Wichtig für den korrekten Kurs; ein schlechter Kompass verursacht EKF-Fehler und Kreiseln.', tips: ['Von Metall, Magneten und hohem Strom fernhalten.', 'Langsam um alle Achsen drehen, bis keine roten Bereiche bleiben.', 'Handys/Lautsprecher fernhalten.'] },
  },
  radio: {
    tr: { title: 'Radyo (RC) kalibrasyonu', body: 'Her RC kanalının min/orta/max değerlerini yakalar; çubuk hareketini otopilota tanıtır. Yapılmazsa kontrol ters/kısıtlı olur.', tips: ['Tüm çubuk ve anahtarları uçlara kadar hareket ettirin.', 'Ortalayıp trim’i ayarlayın.', 'Ters (reverse) yönleri kontrol edin.'] },
    en: { title: 'Radio (RC) calibration', body: 'Captures each RC channel’s min/center/max so the autopilot knows your stick travel. Skip it and control is reversed or limited.', tips: ['Move every stick and switch to their extremes.', 'Center, then set the trim.', 'Check the reverse directions.'] },
    de: { title: 'Funk (RC)-Kalibrierung', body: 'Erfasst Min/Mitte/Max jedes RC-Kanals, damit der Autopilot den Knüppelweg kennt. Ohne sie ist die Steuerung invertiert oder begrenzt.', tips: ['Alle Knüppel und Schalter bis zum Anschlag bewegen.', 'Zentrieren, dann Trimmung setzen.', 'Reverse-Richtungen prüfen.'] },
  },
  rc: {
    tr: { title: 'Alıcı', body: 'Alıcı protokolü (CRSF/ELRS/SBUS…), seri RC girişi, RSSI ve kanal başına yardımcı (aux) fonksiyonları ayarlar. Otopilota alıcının nasıl konuştuğunu ve anahtarların ne yapacağını söyler.', tips: ['UART’a bağlı alıcı için o SERIAL’i RCIN (23) yapın.', 'Aux fonksiyonlarını (RTL, kalkış…) kanallara atayın.', 'RSSI için RSSI_TYPE’ı seçin.'] },
    en: { title: 'Receiver', body: 'Sets the receiver protocol (CRSF/ELRS/SBUS…), serial RC input, RSSI and per-channel aux functions. Tells the autopilot how the receiver talks and what the switches do.', tips: ['For a UART receiver set that SERIAL to RCIN (23).', 'Assign aux functions (RTL, takeoff…) to channels.', 'Pick RSSI_TYPE for signal strength.'] },
    de: { title: 'Empfänger', body: 'Legt Empfängerprotokoll (CRSF/ELRS/SBUS…), seriellen RC-Eingang, RSSI und Aux-Funktionen pro Kanal fest. Sagt dem Autopiloten, wie der Empfänger spricht und was die Schalter tun.', tips: ['Für UART-Empfänger dieses SERIAL auf RCIN (23) setzen.', 'Aux-Funktionen (RTL, Start…) Kanälen zuweisen.', 'RSSI_TYPE für Signalstärke wählen.'] },
  },
  servo: {
    tr: { title: 'Servo çıkışı', body: 'Her çıkış pininin fonksiyonu, min/trim/max, ters yönü ve canlı testi. Yüzey ve motorların doğru pinlere yönlendirilmesini sağlar.', tips: ['SERVOn_FUNCTION’ı kablolamanızla eşleştirin.', 'Test ederken pervaneleri çıkarın.', 'Yön yanlışsa ters (reverse) işaretleyin.', 'Test, fonksiyonu atanmış kanallarda çalışmaz — geçici olarak Disabled yapın.'] },
    en: { title: 'Servo output', body: 'Per-output function, min/trim/max, reverse and a live test. Routes surfaces and motors to the correct pins.', tips: ['Match SERVOn_FUNCTION to your wiring.', 'Remove props before testing.', 'If a direction is wrong, tick reverse.', 'Test doesn’t work on channels with an assigned function — set them to Disabled temporarily.'] },
    de: { title: 'Servo-Ausgang', body: 'Funktion je Ausgang, Min/Trim/Max, Reverse und Live-Test. Leitet Ruder und Motoren an die richtigen Pins.', tips: ['SERVOn_FUNCTION mit der Verkabelung abgleichen.', 'Vor dem Test Propeller entfernen.', 'Bei falscher Richtung Reverse aktivieren.', 'Der Test funktioniert nicht auf zugewiesenen Kanälen — vorübergehend auf Disabled stellen.'] },
  },
  plane: {
    tr: { title: 'Airframe', body: 'Uçak tipini (standart/elevon/V-kuyruk) ve kumanda yüzeyi/motor çıkışlarını eşler. Doğru karışımı kurar; böylece çubuklar doğru yüzeyleri hareket ettirir. Çok motorlu için Ana/Sol/Sağ gaz atanır.', tips: ['Önce uçak tipini seçin.', 'Her yüzeyi bir çıkışa atayın.', 'Diferansiyel itki için Sol/Sağ motoru ayarlayın.'] },
    en: { title: 'Airframe', body: 'Maps the plane type (standard/elevon/V-tail) and the control-surface/motor outputs. Sets the mixing so the sticks move the right surfaces. Multi-motor uses Main/Left/Right throttle.', tips: ['Pick the plane type first.', 'Assign each surface to an output.', 'For differential thrust set Left/Right motors.'] },
    de: { title: 'Airframe', body: 'Ordnet Flugzeugtyp (Standard/Elevon/V-Leitwerk) und Ruder-/Motorausgänge zu. Legt das Mischen fest, damit die Knüppel die richtigen Ruder bewegen. Mehrmotorig über Haupt/Links/Rechts-Gas.', tips: ['Zuerst den Flugzeugtyp wählen.', 'Jedes Ruder einem Ausgang zuweisen.', 'Für Differenzialschub Links/Rechts-Motor setzen.'] },
  },
  battery: {
    tr: { title: 'Pil / Güç', body: 'Voltaj/akım izleyici kurulumu, kapasite ve düşük-pil failsafe seviyeleri. Doğru pil telemetrisi ve güvenlik için.', tips: ['İzleyici tipini seçin (analog/güç modülü).', 'Voltajı bir multimetreye göre kalibre edin.', 'Failsafe voltaj/kapasitesini ayarlayın.'] },
    en: { title: 'Battery / Power', body: 'Voltage/current monitor setup, capacity and low-battery failsafe levels. For accurate battery telemetry and safety.', tips: ['Choose the monitor type (analog/power module).', 'Calibrate voltage against a multimeter.', 'Set the failsafe voltage/capacity.'] },
    de: { title: 'Batterie / Leistung', body: 'Spannungs-/Stromüberwachung, Kapazität und Notfall-Schwellen bei niedrigem Akku. Für genaue Akku-Telemetrie und Sicherheit.', tips: ['Monitortyp wählen (Analog/Power-Modul).', 'Spannung gegen ein Multimeter kalibrieren.', 'Failsafe-Spannung/Kapazität setzen.'] },
  },
  tune: {
    tr: { title: 'PID ayar', body: 'Tutum kontrolü iki iç içe döngüyle çalışır: açı (attitude) döngüsü hedef açıyı dönüş hızına çevirir, hız (rate) döngüsü de o dönüş hızını PID ile motor/servo komutuna dönüştürür — asıl ayar rate PID’lerindedir. P tepkinin gücü, I kalıcı sapmayı (rüzgâr, ağırlık dengesizliği) silen bellek, D ise fren/sönümlemedir. Belirtiler: hızlı titreşimli salınım → P ya da D fazla; yavaş yalpalama → açı P’si fazla; hantal, komutun gerisinde kalan tepki → P düşük. Kopter’de ATC_RAT_* / ATC_ANG_*, uçakta RLL_RATE_* / PTCH_RATE_* parametreleri kullanılır.', tips: ['Önce titreşimi çözün: gyro’ya ulaşan titreşim D terimini motor ısınmasına ve salınıma çevirir — VIBE loguna bakın, INS_GYRO_FILTER’ı çerçeve boyutuna göre ayarlayın.', 'Tek seferde tek ekseni, tek kazancı ve ~%20-30’luk adımlarla değiştirin; her adımı hoverda/düz uçuşta kısa deneyip log ile doğrulayın.', 'Salınım görürseniz önce P’yi %50 düşürüp güvenli bölgeye dönün; oradan yukarı doğru ayarlayın.', 'AUTOTUNE en hızlı başlangıçtır: kopter’de AUTOTUNE modu, uçakta AUTOTUNE ile eksen eksen — sakin havada, geniş alanda uçurun ve sonucu kaydedin.', 'I terimini genelde P ile aynı oranda taşıyın; D’yi küçük tutun (kopter varsayılanının ~2 katını aşmayın).'] },
    en: { title: 'PID tuning', body: 'Attitude control runs as two nested loops: the angle (attitude) loop converts the target angle into a rotation rate, and the rate loop turns that rate into motor/servo commands via PID — the real tuning lives in the rate PIDs. P is the strength of the response, I is the memory that removes steady offsets (wind, CG imbalance), D is the brake/damping. Symptoms: fast buzzing oscillation → P or D too high; slow wobble → angle P too high; sluggish response lagging the sticks → P too low. Copter uses ATC_RAT_* / ATC_ANG_*, plane uses RLL_RATE_* / PTCH_RATE_* parameters.', tips: ['Fix vibration first: vibration reaching the gyro turns the D term into motor heat and oscillation — check the VIBE log and set INS_GYRO_FILTER for your frame size.', 'Change one axis and one gain at a time, in ~20-30% steps; test each step briefly in hover/level flight and verify in the log.', 'If you see oscillation, halve P to get back to a safe region first, then tune upward from there.', 'AUTOTUNE is the fastest starting point: the AUTOTUNE mode on copter, axis-by-axis AUTOTUNE on plane — fly it in calm weather over open space and save the result.', 'Usually scale I together with P; keep D small (avoid exceeding ~2× the copter default).'] },
    de: { title: 'PID-Abstimmung', body: 'Die Lageregelung besteht aus zwei verschachtelten Schleifen: Die Winkelschleife (Attitude) macht aus dem Sollwinkel eine Drehrate, die Ratenschleife setzt diese Rate per PID in Motor-/Servokommandos um — die eigentliche Abstimmung passiert in den Raten-PIDs. P ist die Stärke der Reaktion, I das Gedächtnis gegen bleibende Abweichungen (Wind, Schwerpunkt), D die Bremse/Dämpfung. Symptome: schnelles Zittern → P oder D zu hoch; langsames Wanken → Winkel-P zu hoch; träge, den Knüppeln hinterherhängende Reaktion → P zu niedrig. Copter nutzt ATC_RAT_* / ATC_ANG_*, Flugzeug RLL_RATE_* / PTCH_RATE_*.', tips: ['Zuerst Vibrationen beheben: Vibration am Gyro macht aus dem D-Term Motorhitze und Schwingen — VIBE-Log prüfen, INS_GYRO_FILTER zur Rahmengröße passend setzen.', 'Immer nur eine Achse und einen Wert ändern, in ~20-30%-Schritten; jeden Schritt kurz im Schwebe-/Geradeausflug testen und im Log prüfen.', 'Bei Schwingen zuerst P halbieren, um in den sicheren Bereich zurückzukehren; von dort nach oben abstimmen.', 'AUTOTUNE ist der schnellste Einstieg: AUTOTUNE-Modus beim Copter, achsenweise beim Flugzeug — bei ruhigem Wetter über freiem Gelände fliegen und das Ergebnis speichern.', 'I meist im gleichen Verhältnis wie P mitführen; D klein halten (nicht über ~2× des Copter-Standards).'] },
  },
  tecs: {
    tr: { title: 'TECS (Uçak)', body: 'TECS (Toplam Enerji Kontrol Sistemi), irtifa ve hava hızını tek bir enerji problemi olarak ele alır: gaz toplam enerjiyi (yükseklik + hız), pitch ise bu enerjinin irtifa ile hız arasındaki dağılımını yönetir. Tırmanırken hız kaybını (stall), alçalırken aşırı hızı önler; AUTO / FBWB / CRUISE / LOITER gibi otomatik modlarda hız–irtifa koordinasyonunu bu denetleyici sağlar. Yanlış TECS ayarı, salınımlı irtifa tutuşu ya da tırmanışta tehlikeli hız kaybı olarak kendini gösterir.', tips: ['Önce hız zarfını girin: AIRSPEED_CRUISE seyir hızı, AIRSPEED_MIN stall hızının ~%20 üstü, AIRSPEED_MAX yapısal limitin altında olmalı.', 'TECS_CLMB_MAX ve TECS_SINK_MAX aracın gerçekten sürdürebildiği değerler olmalı — iyimser tırmanma değeri hız kaybettirir. TECS_SINK_MIN = rölantide doğal süzülme hızıdır.', 'TECS_SPDWEIGHT enerji önceliği: 0 = irtifa öncelikli, 1 = dengeli (varsayılan), 2 = hız öncelikli (stall’a karşı en güvenli; motorsuz planörde 2 kullanın).', 'Hava hızı sensörü yok ya da kalibre değilse önce onu çözün — TECS kötü hız verisiyle doğru çalışamaz.', 'TECS_TIME_CONST ve sönümleme kazançlarını küçük adımlarla değiştirin; her değişikliği FBWB/AUTO’da irtifa ve hız tutuşunu izleyerek doğrulayın.'] },
    en: { title: 'TECS (Plane)', body: 'TECS (Total Energy Control System) treats altitude and airspeed as one energy problem: throttle controls the total energy (height + speed), while pitch distributes that energy between altitude and airspeed. This prevents stalling in climbs and overspeeding in descents; in automatic modes such as AUTO / FBWB / CRUISE / LOITER this controller does the speed–height coordination. A badly tuned TECS shows up as oscillating altitude hold or dangerous speed loss while climbing.', tips: ['Define the speed envelope first: AIRSPEED_CRUISE for cruise, AIRSPEED_MIN ~20% above stall, AIRSPEED_MAX below the structural limit.', 'TECS_CLMB_MAX and TECS_SINK_MAX must be rates the aircraft can actually sustain — an optimistic climb value bleeds airspeed. TECS_SINK_MIN is the natural glide sink rate at idle.', 'TECS_SPDWEIGHT sets the energy priority: 0 = height first, 1 = balanced (default), 2 = speed first (safest against stall; use 2 on unpowered gliders).', 'If there is no (or an uncalibrated) airspeed sensor, fix that first — TECS cannot work well with bad speed data.', 'Change TECS_TIME_CONST and the damping gains in small steps; verify each change in FBWB/AUTO by watching altitude and speed hold.'] },
    de: { title: 'TECS (Flugzeug)', body: 'TECS (Total Energy Control System) behandelt Höhe und Fluggeschwindigkeit als ein gemeinsames Energieproblem: Das Gas regelt die Gesamtenergie (Höhe + Geschwindigkeit), der Pitch verteilt diese Energie zwischen Höhe und Geschwindigkeit. Das verhindert Strömungsabriss im Steigflug und Überschreitung im Sinkflug; in Automatikmodi wie AUTO / FBWB / CRUISE / LOITER übernimmt dieser Regler die Koordination. Ein schlecht abgestimmtes TECS zeigt sich als schwingende Höhenhaltung oder gefährlicher Geschwindigkeitsverlust im Steigen.', tips: ['Zuerst den Geschwindigkeitsbereich festlegen: AIRSPEED_CRUISE als Reisegeschwindigkeit, AIRSPEED_MIN ~20% über der Stallgeschwindigkeit, AIRSPEED_MAX unter dem Strukturlimit.', 'TECS_CLMB_MAX und TECS_SINK_MAX müssen real erreichbare Raten sein — ein optimistischer Steigwert kostet Geschwindigkeit. TECS_SINK_MIN ist die natürliche Sinkrate im Leerlauf.', 'TECS_SPDWEIGHT setzt die Energiepriorität: 0 = Höhe zuerst, 1 = ausgewogen (Standard), 2 = Geschwindigkeit zuerst (am sichersten gegen Stall; bei Seglern 2 verwenden).', 'Ohne (oder mit unkalibriertem) Fahrtmesser zuerst diesen in Ordnung bringen — mit schlechten Geschwindigkeitsdaten kann TECS nicht sauber arbeiten.', 'TECS_TIME_CONST und die Dämpfungswerte in kleinen Schritten ändern; jede Änderung in FBWB/AUTO anhand von Höhen- und Geschwindigkeitshaltung prüfen.'] },
  },
  modes: {
    tr: { title: 'Uçuş modları', body: 'Her anahtar pozisyonuna bir uçuş modu ve mod kanalını atar. Uçarken MANUAL/FBWA/AUTO/RTL arasında geçmenizi sağlar.', tips: ['Mod kanalını (FLTMODE_CH) ayarlayın.', 'Anahtarı oynatıp aktif pozisyonun vurgulandığını görün.', 'Mutlaka bir MANUAL/STABILIZE ve RTL bulundurun.'] },
    en: { title: 'Flight modes', body: 'Assigns a flight mode to each switch position and the mode channel. Lets you switch between MANUAL/FBWA/AUTO/RTL in flight.', tips: ['Set the mode channel (FLTMODE_CH).', 'Move the switch and confirm the active position highlights.', 'Always keep a MANUAL/STABILIZE and an RTL.'] },
    de: { title: 'Flugmodi', body: 'Weist jeder Schalterposition einen Flugmodus und den Moduskanal zu. Ermöglicht das Wechseln zwischen MANUAL/FBWA/AUTO/RTL im Flug.', tips: ['Moduskanal (FLTMODE_CH) setzen.', 'Schalter bewegen und aktive Position prüfen.', 'Immer ein MANUAL/STABILIZE und ein RTL vorhalten.'] },
  },
  failsafe: {
    tr: { title: 'Failsafe', body: 'RC/GCS/pil kaybında aracın ne yapacağını belirler. Güvenliğin temeli — kaçışları ve kazaları önler.', tips: ['RC failsafe’i RTL/İniş yapın.', 'Tezgahta test edin (motor/pervane olmadan).', 'Pil failsafe’ini ayarlayın.'] },
    en: { title: 'Failsafe', body: 'Defines what the vehicle does on loss of RC/GCS/battery. The foundation of safety — it prevents flyaways and crashes.', tips: ['Set RC failsafe to RTL/Land.', 'Test on the bench (no props).', 'Set the battery failsafe.'] },
    de: { title: 'Failsafe', body: 'Legt fest, was das Fahrzeug bei Verlust von RC/GCS/Akku tut. Grundlage der Sicherheit — verhindert Wegflüge und Abstürze.', tips: ['RC-Failsafe auf RTL/Landen setzen.', 'Auf der Werkbank testen (ohne Propeller).', 'Akku-Failsafe setzen.'] },
  },
  serial: {
    tr: { title: 'Seri portlar', body: 'Her UART için baud hızı ve protokol. Telemetri, GPS, alıcı ve çevre birimlerini bağlamak için kullanılır.', tips: ['İki uçta da baud eşleşmeli.', 'Seri alıcılar için RCIN (23).', 'OSD/gözlük için MSP/DisplayPort.'] },
    en: { title: 'Serial ports', body: 'Baud rate and protocol for each UART. Used to connect telemetry, GPS, receiver and peripherals.', tips: ['Baud must match on both ends.', 'RCIN (23) for serial receivers.', 'MSP/DisplayPort for OSD/goggles.'] },
    de: { title: 'Serielle Ports', body: 'Baudrate und Protokoll je UART. Zum Anschluss von Telemetrie, GPS, Empfänger und Peripherie.', tips: ['Baud muss an beiden Enden gleich sein.', 'RCIN (23) für serielle Empfänger.', 'MSP/DisplayPort für OSD/Brille.'] },
  },
  osd: {
    tr: { title: 'OSD', body: 'Ekran üstü gösterge düzeni (analog + HD MSP DisplayPort). Telemetriyi FPV görüntünüzde görmenizi sağlar.', tips: ['OSD_TYPE’ı etkinleştirin.', 'HD için SERIAL’i DisplayPort (42) yapın.', 'Öğeleri sürükleyin; gözlük güvenli bölgelerine dikkat.'] },
    en: { title: 'OSD', body: 'On-screen display layout (analog + HD MSP DisplayPort). Lets you see telemetry over your FPV feed.', tips: ['Enable OSD_TYPE.', 'For HD set the SERIAL to DisplayPort (42).', 'Drag elements; mind the goggle-safe zones.'] },
    de: { title: 'OSD', body: 'Bildschirmanzeige-Layout (analog + HD MSP DisplayPort). Zeigt Telemetrie über dem FPV-Bild.', tips: ['OSD_TYPE aktivieren.', 'Für HD das SERIAL auf DisplayPort (42) setzen.', 'Elemente ziehen; Brillen-Sicherzonen beachten.'] },
  },
  gps: {
    tr: { title: 'GPS', body: 'GPS alıcı tipi, ikinci GPS, otomatik seçim/blend ve öncelik. Doğru konum ve çift-GPS yedekliliği için.', tips: ['Çoğu alıcı için AUTO ya da uBlox.', 'İki GPS varsa “Blend” ikisini birleştirir.', 'Her iki GPS_TYPE’ı da ayarlayın.'] },
    en: { title: 'GPS', body: 'GPS receiver type, second GPS, auto-switch/blend and priority. For accurate position and dual-GPS redundancy.', tips: ['AUTO or uBlox for most receivers.', 'With two GPS, “Blend” fuses both.', 'Set both GPS types.'] },
    de: { title: 'GPS', body: 'GPS-Empfängertyp, zweites GPS, Auto-Umschaltung/Blend und Priorität. Für genaue Position und GPS-Redundanz.', tips: ['AUTO oder uBlox für die meisten Empfänger.', 'Mit zwei GPS fusioniert „Blend“ beide.', 'Beide GPS-Typen setzen.'] },
  },
  lidar: {
    tr: { title: 'Lidar / Mesafe Sensörü', body: 'Barometre onlarca santim sürüklenirken lidar, yüzeye olan gerçek mesafeyi santim hassasiyetinde ölçer. Uçakta doğru irtifada flare yaparak hassas iniş sağlar; kopterde alçak irtifada irtifa tutuşunu keskinleştirir, yüzey takibi ve oto görevlerde arazi takibi yapar. Veri, EK3_RNG_USE_HGT eşiğinin altında EKF’nin irtifa kaynağı da olabilir. Bu ekran tüm zinciri kapsar: tip → seri port → yeniden başlat → yönelim/menzil → kullanan sistemler; canlı okuma sensörün çalıştığının kanıtıdır.', tips: ['Kurulum sırası: tipi seçin, seri sensörse portu bu ekrandan atayın, kartı yeniden başlatıp parametreleri yeniden indirin — yönelim ve menzil alanları ancak o zaman görünür.', 'Min/max’ı veri sayfasından girin; gerçek menzil yüzeye bağlıdır — koyu, mat, su ya da uzun çim yüzeylerde ciddi kısalır.', 'Doğrulama: aracı elle kaldırın, canlı okuma birebir izlemeli. RNGFND1_GNDCLEAR = araç yerde dururken okunan mesafe (iniş algısı için kritik).', 'Uçakta RNGFND_LANDING ile flare doğru yükseklikte başlar; kopterde SURFTRAK_MODE / WPNAV_RFND_USE arazi takibi sağlar.', 'EK3_RNG_USE_HGT’yi engebeli arazide dikkatli kullanın — her tümsek irtifa komutu gibi yansır. Parlak güneş ve su üstü, optik lidarları yanıltabilir.'] },
    en: { title: 'Lidar / Rangefinder', body: 'While the barometer drifts by tens of centimetres, a lidar measures the true distance to the surface with centimetre accuracy. On planes it enables precise landing by flaring at the right height; on copters it sharpens low-altitude hold, does surface tracking and terrain following in auto missions. Below the EK3_RNG_USE_HGT threshold it can even become the EKF height source. This screen covers the whole chain: type → serial port → reboot → orientation/range → consuming systems; the live reading is the proof the sensor works.', tips: ['Setup order: pick the type, assign the port here for serial sensors, reboot and re-download parameters — only then do the orientation and range fields appear.', 'Enter min/max from the datasheet; real range depends on the surface — dark, matte, water or tall grass surfaces shorten it badly.', 'Verify: lift the vehicle by hand, the live reading should track exactly. RNGFND1_GNDCLEAR = the reading while sitting on the ground (critical for landing detection).', 'On planes RNGFND_LANDING starts the flare at the right height; on copters SURFTRAK_MODE / WPNAV_RFND_USE give terrain following.', 'Use EK3_RNG_USE_HGT carefully over rough terrain — every bump reflects like an altitude command. Bright sun and water can fool optical lidars.'] },
    de: { title: 'Lidar / Abstandssensor', body: 'Während das Barometer um Dutzende Zentimeter driftet, misst ein Lidar den echten Abstand zur Oberfläche zentimetergenau. Beim Flugzeug ermöglicht es die Präzisionslandung mit Flare in der richtigen Höhe; beim Copter schärft es die Höhenhaltung in Bodennähe, macht Oberflächenverfolgung und Geländefolge in Auto-Missionen. Unterhalb der EK3_RNG_USE_HGT-Schwelle kann es sogar EKF-Höhenquelle werden. Dieser Bildschirm deckt die ganze Kette ab: Typ → serieller Port → Neustart → Ausrichtung/Reichweite → nutzende Systeme; die Live-Anzeige beweist, dass der Sensor arbeitet.', tips: ['Reihenfolge: Typ wählen, bei seriellen Sensoren den Port hier zuweisen, neu starten und Parameter neu laden — erst dann erscheinen Ausrichtungs- und Reichweitenfelder.', 'Min/Max laut Datenblatt eintragen; die reale Reichweite hängt von der Oberfläche ab — dunkle, matte, Wasser- oder Grasflächen verkürzen sie stark.', 'Prüfen: Fahrzeug von Hand anheben, die Live-Anzeige muss exakt folgen. RNGFND1_GNDCLEAR = Messwert am Boden (wichtig für die Landeerkennung).', 'Beim Flugzeug startet RNGFND_LANDING den Flare in der richtigen Höhe; beim Copter geben SURFTRAK_MODE / WPNAV_RFND_USE Geländefolge.', 'EK3_RNG_USE_HGT über unebenem Gelände vorsichtig nutzen — jede Bodenwelle wirkt wie ein Höhenkommando. Grelle Sonne und Wasser können optische Lidars täuschen.'] },
  },
  flow: {
    tr: { title: 'Optik Akış', body: 'GPS’siz konum tutuşu için optik akış sensörü, yönelimi ve konumu. İç mekan/alçak irtifada işe yarar.', tips: ['Bir mesafe sensörü (rangefinder) gerekir.', 'FLOW_TYPE’ı sensörünüze göre seçin.', 'Uçuşta ölçek katsayılarını kalibre edin.'] },
    en: { title: 'Optical flow', body: 'Optical-flow sensor, orientation and position for GPS-denied position hold. Useful indoors/at low altitude.', tips: ['A rangefinder is required.', 'Set FLOW_TYPE to your sensor.', 'Calibrate the scalers in flight.'] },
    de: { title: 'Optischer Fluss', body: 'Optical-Flow-Sensor, Ausrichtung und Position für GPS-freies Positionshalten. Nützlich in Innenräumen/niedriger Höhe.', tips: ['Ein Rangefinder ist erforderlich.', 'FLOW_TYPE auf Ihren Sensor setzen.', 'Skalierer im Flug kalibrieren.'] },
  },
  adsb: {
    tr: { title: 'ADS-B', body: 'ADS-B alıcı tipi ve çarpışma önleme (avoidance). İnsanlı trafiği görüp kaçınmak için.', tips: ['ADSB_TYPE’ı alıcınıza göre ayarlayın.', 'Otomatik kaçınma için AVD’yi etkinleştirin.', 'Kaçınma mesafelerini ayarlayın.'] },
    en: { title: 'ADS-B', body: 'ADS-B receiver type and collision avoidance. To see and avoid manned traffic.', tips: ['Set ADSB_TYPE to your receiver.', 'Enable AVD for automatic avoidance.', 'Set the avoidance distances.'] },
    de: { title: 'ADS-B', body: 'ADS-B-Empfängertyp und Kollisionsvermeidung. Um bemannten Verkehr zu erkennen und auszuweichen.', tips: ['ADSB_TYPE auf Ihren Empfänger setzen.', 'AVD für automatisches Ausweichen aktivieren.', 'Ausweichabstände setzen.'] },
  },
  sik: {
    tr: { title: 'SiK telemetri radyo', body: 'SiK radyo linkinin canlı sinyal/gürültü kalitesi. Uzağa uçmadan önce link sağlığını kontrol edin.', tips: ['RSSI ile gürültü farkı yüksekse link iyidir.', 'Antenleri dik ve birbirine paralel tutun.', 'Güç/air-speed radyo aracından ayarlanır.'] },
    en: { title: 'SiK telemetry radio', body: 'Live signal/noise quality of the SiK radio link. Check link health before flying far.', tips: ['A high RSSI-minus-noise margin means a good link.', 'Keep antennas vertical and parallel.', 'Set power/air-speed in the radio tool.'] },
    de: { title: 'SiK-Telemetriefunk', body: 'Live Signal-/Rauschqualität der SiK-Funkverbindung. Vor weiten Flügen die Linkqualität prüfen.', tips: ['Hoher RSSI-minus-Rausch-Abstand = gute Verbindung.', 'Antennen senkrecht und parallel halten.', 'Leistung/Air-Speed im Funk-Tool setzen.'] },
  },
  params: {
    tr: { title: 'Parametreler', body: 'Otopilotun tüm parametreleri: arama, düzenleme, .param kaydet/yükle ve dosya-araç karşılaştırma. İnce ayar ve yedekleme için.', tips: ['Önce parametreleri indirin.', 'Değişiklik öncesi yedek alın (.param).', 'Bir dosyayı seçili şekilde uygulamak için Karşılaştır’ı kullanın.'] },
    en: { title: 'Parameters', body: 'Every autopilot parameter: search, edit, save/load .param, and compare a file against the vehicle. For fine tuning and backups.', tips: ['Download the parameters first.', 'Back up (.param) before changing.', 'Use Compare to selectively apply a saved file.'] },
    de: { title: 'Parameter', body: 'Alle Autopilot-Parameter: suchen, bearbeiten, .param speichern/laden und Datei mit Fahrzeug vergleichen. Für Feinabstimmung und Backups.', tips: ['Zuerst die Parameter herunterladen.', 'Vor Änderungen sichern (.param).', 'Mit Vergleichen eine Datei gezielt anwenden.'] },
  },
};
